services:
  mongodb:
    image: mongo:latest
    container_name: mongo-local
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro  # Mount init script
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydb
